name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: jgierer12/npm-auth-gpr@v1.0.1
      with:
      # The token used for authentication. Usually, this should be your `secrets.GITHUB_TOKEN`
          token: ${{secrets.GITHUB_TOKEN}}
    - run: npm install
    - run: npm publish
